source 'https://rubygems.org'
gem 'rails', '4.2.1'
gem 'pg'
gem 'carrierwave'
gem 'mini_magick'
gem 'fog'
gem 'authlogic'
gem 'will_paginate'
gem 'sass-rails', '~> 5.0'
gem 'bootstrap-sass', '~> 3.3.4'
gem 'bootstrap-will_paginate'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'puma'

group :development, :test do
  gem 'byebug'
  gem 'better_errors'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
